### ISSUE TITLE
FFmpeg causing issues maybe

### ISSUE THREAD

**Issue by gimmeAll** [warren-bank/node-hls-downloader-tubitv#1]
I dont know specifically what is causing issues other than some command sent to FFmpeg is not fulfilled correctly, maybe. All I know is that I entered the following command and the very bottom resulted from it. Please help I just wanna watch this show offline

 -------------------------------------------------------------
tubidl -mc 5 -u https://tubitv.com/series/926/dan-vs
-------------------------------------------------------------

starting download of 405 video data files..
done

download complete.

starting ffmpeg conversion of HLS stream to mp4 file..
ffmpeg error:
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Windows\\system32\\cmd.exe',
  path: 'C:\\Windows\\system32\\cmd.exe',
  spawnargs: [
    '/d',
    '/s',
    '/c',
    '"ffmpeg -nostats -hide_banner -loglevel panic -allowed_extensions ALL -i "D:\\aaaa\\Dan Vs.\\S01E01 - The Wolf-Man\\hls\\master.m3u8" -c copy -movflags +faststart "D:\\aaaa\\Dan Vs.\\S01E01 - The Wolf-Man\\mp4\\video.mp4""'
  ],
  cmd: 'ffmpeg -nostats -hide_banner -loglevel panic -allowed_extensions ALL -i "D:\\aaaa\\Dan Vs.\\S01E01 - The Wolf-Man\\hls\\master.m3u8" -c copy -movflags +faststart "D:\\aaaa\\Dan Vs.\\S01E01 - The Wolf-Man\\mp4\\video.mp4"'
}

**Comment by warren-bank** [comment]
I'm actually pleasantly surprised that this utility is (apparently) still working properly; the website hasn't made any breaking changes that would require an update to the utility.

looks as though:
* OK: website scraped for HLS url
* OK: HLS url downloaded (manifest, all video segments, all audio segments, all subtitle segments, etc)
* fail: [`ffmpeg`](https://github.com/warren-bank/node-hls-downloader-tubitv#requirements) not found on _PATH_
  - would I be right to assume that the following doesn't print any version number?: `ffmpeg --version`
  - if so, just download an [`ffmpeg` binary](https://github.com/BtbN/FFmpeg-Builds/releases) and save it to a directory included in your _PATH_

**Comment by warren-bank** [comment]
PS:
* assuming that the directory still exists:
  ```text
    "D:\aaaa\Dan Vs.\S01E01 - The Wolf-Man"
  ```
* once you have a working copy of `ffmpeg`:
  - you can complete the last step and convert the offline HLS video to an mp4 by running:
    ```text
      ffmpeg -nostats -hide_banner -loglevel panic -allowed_extensions ALL -i "D:\aaaa\Dan Vs.\S01E01 - The Wolf-Man\hls\master.m3u8" -c copy -movflags +faststart "D:\aaaa\Dan Vs.\S01E01 - The Wolf-Man\mp4\video.mp4"
    ```
