### ISSUE TITLE
Assertion Error: Missing Data Fields in Video Object Metadata for Movie Video Stream In Server Response

### ISSUE THREAD

**Issue by DebianJK** [warren-bank/node-hls-downloader-tubitv#10]
Download via bash script error:
Error: Assertion Error: missing data fields in video object metadata for movie video stream in server response at URL: 'https://tubitv.com/movies/580545/priest'
    at process_video_data (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:167:15)
    at process_html (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:105:15)
    at process_url (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:67:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async process_argv (/usr/local/lib/node_modules/@warren-bank/node-hls-downloader-tubitv/lib/process_cli.js:379:7)

In addition, the following URL also produced similar error:
https://tubitv.com/movies/522096/stealth
https://tubitv.com/movies/642405/colombiana
https://tubitv.com/movies/100015519/xxx

Bash Script:
tubidl --directory-prefix /usr/local/download -mf 1 -mc 3 --url $URL

With kind regards

**Comment by warren-bank** [comment]
I haven't looked at this repo in a very long time, but just quickly looking at your video examples:

* [Priest](https://tubitv.com/movies/580545/priest)
  - content unavailable
* [Stealth](https://tubitv.com/movies/522096/stealth)
  - DRM protected streams only
* [Colombiana](https://tubitv.com/movies/642405/colombiana)
  - content unavailable
* [XXX](https://tubitv.com/movies/100015519/xxx)
  - content unavailable

Suffice it to say, videos having its "content unavailable" cannot be accessed.

Videos having DRM protection cannot be downloaded by this utility because it doesn't support DRM protected HLS streams.
If you want to see all of the available DRM protected HLS streams and possibly download them using a different utility, my [Greasemonkey userscript for TubiTV](https://github.com/warren-bank/crx-Tubi-TV) will display that information.

**Comment by DebianJK** [comment]
I was able to watch:
https://tubitv.com/movies/642405/colombiana
https://tubitv.com/movies/100015519/xxx
using Firefox (Debian 11.9 Cinnamon GUI) but not able to download using tubidl.

**Comment by warren-bank** [comment]
recently?

I've loaded both pages in Chrome and FF..
and all it shows me is "content unavailable".

Are you in the US?
Maybe I'm geo-restricted (being that I'm in the US), whereas you're not?

Although I highly doubt this would matter..
what is the ["User-Agent"](http://httpbin.org/get) of your FF?

**Comment by DebianJK** [comment]
User-Agent:
"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
I am in Canada!
![Colombiana](https://github.com/warren-bank/node-hls-downloader-tubitv/assets/40860840/f0e5b7e1-6f81-4064-ad53-77b397b1e27f)

**Comment by warren-bank** [comment]
I'll test a VPN..

**Comment by warren-bank** [comment]
OK.. that was the problem.
"User-Agent" had nothing to do with it.

Using a VPN to make TubiTV think that I'm also in Canada..
I was able to watch both movies ([Colombiana](https://tubitv.com/movies/642405/colombiana) and [XXX](https://tubitv.com/movies/100015519/xxx)).

The issue with downloading these movies is DRM.
Both of these movies are DRM protected.
(Refer to previous comments about DRM.)

**Comment by DebianJK** [comment]
> If you want to see all of the available DRM protected HLS streams and possibly download them using a different utility

Okay! Do you know of any other utility able to download DRM protected streams from [https://tubitv.com](url)?

**Comment by warren-bank** [comment]
short answer: no

longer answer: the utility doesn't need to specifically be for TubiTV.. you can get all of the relevant URLs from my userscript.. and plug them into the generic utility.. I'm just not aware (off-hand) of any generic utility that will convert HLS+DRM to MP4.

**Comment by DebianJK** [comment]
Thanks!

**Comment by warren-bank** [comment]
https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom

..does _not_ look easy

**Comment by DebianJK** [comment]
Well! At least someone is trying....Goodnight!
