### ISSUE TITLE
Assertion Error: missing data fields in video object metadata for movie video stream in server response at URL: 

### ISSUE THREAD

**Issue by psd41** [warren-bank/node-hls-downloader-tubitv#4]
I've noticed quite a few titles come back with the error (example included for film hardcore):
Assertion Error: missing data fields in video object metadata for movie video stream in server response at URL: 'https://tubitv.com/movies/670431/hardcore'
It looks as if most of the new stuff is having this problem.

**Comment by warren-bank** [comment]
duplicate #3 

checked your particular movie link..
* all video sources use widevine
* [userscript](https://github.com/warren-bank/crx-Tubi-TV) lists direct links for all
  - as well as links to "cast" each video for playback in [an Android app](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver)
